baseURL = "https://canon.thefoldwithin.earth/"
languageCode = "en-us"
title = "Mark Randall Havens"
theme = "terminal"
paginate = 5

[params]
  subtitle = "The Empathic Technologist"
  
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  themeColor = "dark"

  # if you set this to 0, only headings with level 1-3 will be shown.
  showMenuItems = 4

  # show word count and read time ?
  showWordCount = true
  showReadTime = true

  # Set terminal color (green, orange, red, pink, blue, etc)
  terminalTheme = "green"

  # Center logo and title?
  centerTheme = true

[params.logo]
  logoText = "mark_randall_havens@empathic-technologist:~#"
  logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "codex"
    name = "Codex"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "papers"
    name = "Papers"
    url = "/tags/paper/"
    weight = 20
  [[menu.main]]
    identifier = "essays"
    name = "Essays"
    url = "/tags/essay/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[permalinks]
  papers = "/:filename/"
